import { expect, test } from "bun:test";
import { mkdir, mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { BackendCommandRunner } from "../src/engine/backend";
import { auditHarness } from "../src/engine/harness-audit";
import { collectHarnessAuditCorpus } from "../src/engine/harness-audit-evidence";

test("generated Swift build output cannot displace live nested guidance", async () => {
  const targetDir = await mkdtemp(join(tmpdir(), "farrier-audit-swift-build-output-"));
  await mkdir(join(targetDir, "apps/macos/.build"), { recursive: true });
  await mkdir(join(targetDir, "apps/shared/docs"), { recursive: true });
  await writeFile(join(targetDir, "apps/macos/.build/AGENTS.md"),
    "Read `docs/generated.md` before changing generated output.\n");
  await writeFile(join(targetDir, "apps/shared/AGENTS.md"),
    "Read `docs/required.md` before changing shared code.\n");
  await writeFile(join(targetDir, "apps/shared/docs/required.md"), "# Required\n");

  const corpus = await collectHarnessAuditCorpus(targetDir);
  const report = await auditHarness({ targetDir, mode: "quick" });

  expect(corpus.documents.some((item) => item.path.includes("/.build/"))).toBeFalse();
  expect(corpus.documents.map((item) => item.path)).toContain("apps/shared/AGENTS.md");
  expect(corpus.checks).toContainEqual(expect.objectContaining({
    description: "Checked referenced path apps/shared/docs/required.md.",
    result: "regular file exists",
  }));
  expect(report.recommendations).toEqual([]);
  expect(report.metrics.modelCalls).toBe(0);
});

test("installed Elixir dependencies cannot produce harness findings", async () => {
  const targetDir = await mkdtemp(join(tmpdir(), "farrier-audit-elixir-deps-"));
  await mkdir(join(targetDir, "elixir/deps/phoenix"), { recursive: true });
  await mkdir(join(targetDir, "elixir/docs"), { recursive: true });
  await writeFile(join(targetDir, "elixir/deps/phoenix/AGENTS.md"),
    "Run `scripts/check.sh` before completing dependency work.\n");
  await writeFile(join(targetDir, "elixir/AGENTS.md"),
    "Read `docs/live.md` before changing the live application.\n");
  await writeFile(join(targetDir, "elixir/docs/live.md"), "# Live application\n");

  const corpus = await collectHarnessAuditCorpus(targetDir);
  const report = await auditHarness({ targetDir, mode: "quick" });
  const dependencyLine = corpus.lines.find((line) => line.path.includes("/deps/")
    && line.text.includes("scripts/check.sh"));
  const dependencyCheck = corpus.checks.find((check) =>
    check.description === "Checked referenced path elixir/deps/phoenix/scripts/check.sh.");
  const runner: BackendCommandRunner = async () => ({
    exitCode: 0,
    stderr: "",
    stdout: JSON.stringify({ recommendations: [{
      id: "guidance:dependency-script-missing",
      layer: "guidance",
      severity: "high",
      title: "Dependency guidance requires a missing script",
      defect: "The dependency guidance requires elixir/deps/phoenix/scripts/check.sh, but that path is missing.",
      evidence: [dependencyLine?.id ?? "missing-dependency-line"],
      counterchecks: [dependencyCheck?.id ?? "missing-dependency-check"],
      artifact: dependencyLine?.path ?? "elixir/deps/phoenix/AGENTS.md",
      change: "Remove the required script instruction from the dependency-owned AGENTS.md.",
      risk: "Following the dependency instruction would fail before its check runs.",
      uncertainty: "The dependency checkout could be regenerated by its package manager.",
    }] }),
  });
  const baseline = await auditHarness({ targetDir, mode: "baseline", backend: "codex", runner });

  expect(report.recommendations).toEqual([]);
  expect(baseline.recommendations).toEqual([]);
  expect(corpus.documents.map((item) => item.path)).toContain("elixir/AGENTS.md");
  expect(corpus.documents.some((item) => item.path.includes("/deps/"))).toBeFalse();
  expect(corpus.checks).toContainEqual(expect.objectContaining({
    description: "Checked referenced path elixir/docs/live.md.",
    result: "regular file exists",
  }));
  expect(report.metrics.modelCalls).toBe(0);
});
