import { describe, expect, test } from "bun:test";
import { escapeTomlMultiline, playbookFiles, renderClaudeSubagentMd, renderSubagentToml, unescapeTomlMultiline } from "../src/engine/render-playbook";
import { validateRegistryItem } from "../src/registry/schema";
import type { PackPlaybook, PackSubagent } from "../src/packs/types";

const reviewer: PackSubagent = {
  name: "ux_hig_reviewer",
  description: 'Read-only UX reviewer that judges rendered screenshots against "HIG".',
  sandboxMode: "read-only",
  developerInstructions: "Review like a human design reviewer.\nNever approve a screen you have not seen rendered."
};

const playbook: PackPlaybook = {
  orchestrator: {
    name: "ios-prd-playbook",
    description: "Build an iOS app from an approved PRD through phased gates.",
    body: "# iOS PRD playbook\n\nRun phases in order.",
    references: [{ name: "gates.md", content: "# Gate catalog\n" }]
  },
  phases: [
    {
      name: "ux-skeleton-phase",
      description: "Build every screen as a navigable skeleton before feature logic.",
      body: "Skeleton first."
    }
  ]
};

describe("playbookFiles", () => {
  test("renders codex and claude layouts for both agents", async () => {
    const files = await playbookFiles({ playbook, subagents: [reviewer], agents: ["claude", "codex"] });
    const paths = files.map((file) => file.path).sort();

    expect(paths).toEqual([
      ".agents/skills/ios-prd-playbook/SKILL.md",
      ".agents/skills/ios-prd-playbook/agents/ux_hig_reviewer.toml",
      ".agents/skills/ios-prd-playbook/references/gates.md",
      ".agents/skills/ux-skeleton-phase/SKILL.md",
      ".claude/agents/ux-hig-reviewer.md",
      ".claude/skills/ios-prd-playbook/SKILL.md",
      ".claude/skills/ios-prd-playbook/references/gates.md",
      ".claude/skills/ux-skeleton-phase/SKILL.md"
    ]);

    const skillMd = files.find((file) => file.path === ".agents/skills/ios-prd-playbook/SKILL.md")!.content;
    expect(skillMd).toStartWith("---\nname: ios-prd-playbook\n");
    expect(skillMd).toContain('description: "Build an iOS app from an approved PRD through phased gates."');
    expect(skillMd).toContain("# iOS PRD playbook");
  });

  test("subagents without a playbook render Claude-only", async () => {
    const files = await playbookFiles({ subagents: [reviewer], agents: ["claude", "codex"] });
    expect(files.map((file) => file.path)).toEqual([".claude/agents/ux-hig-reviewer.md"]);
  });

  test("gate checks render as declarative gates.json plus the executable engine-owned checker", async () => {
    const withChecks = {
      ...playbook,
      gateChecks: [
        {
          gateId: "evidence-before-complete",
          description: "Exit evidence for evidence-before-complete",
          rules: [{ kind: "file-exists" as const, path: "EVIDENCE_LEDGER.csv" }]
        }
      ]
    };
    const files = await playbookFiles({ playbook: withChecks, agents: ["codex"] });
    const gatesJson = files.find((file) => file.path === ".agents/skills/ios-prd-playbook/gates/gates.json");
    const checker = files.find((file) => file.path === ".agents/skills/ios-prd-playbook/gates/check.py");

    expect(JSON.parse(gatesJson!.content).gates[0].rules[0].path).toBe("EVIDENCE_LEDGER.csv");
    expect(checker?.mode).toBe(0o755);
    expect(checker?.content).toContain("engine-owned; regenerated by farrier");
    // No checks -> no gates directory at all.
    const bare = await playbookFiles({ playbook, agents: ["codex"] });
    expect(bare.some((file) => file.path.includes("/gates/"))).toBe(false);
  });

  test("toml output escapes quotes and carries the read-only default", () => {
    const toml = renderSubagentToml({ ...reviewer, sandboxMode: undefined });
    expect(toml).toContain('name = "ux_hig_reviewer"');
    expect(toml).toContain('sandbox_mode = "read-only"');
    expect(toml).toContain('\\"HIG\\"');
    expect(toml).toContain('developer_instructions = """');
  });

  test("claude subagent markdown uses kebab name and read-only tools", () => {
    const md = renderClaudeSubagentMd(reviewer);
    expect(md).toStartWith("---\nname: ux-hig-reviewer\n");
    expect(md).toContain("tools: Read, Grep, Glob, Bash");
    expect(md).toContain("Never approve a screen");
  });
});

describe("registry pack payload with playbook and subagents", () => {
  const base = {
    schemaVersion: 1,
    type: "pack",
    name: "ios-playbook",
    version: "1.0.0",
    pack: {
      detect: {},
      skills: [],
      hooks: [],
      verbs: { check: "true", checkFast: "true", test: "true", fmt: "true" },
      subagents: [reviewer],
      playbook
    }
  };

  test("accepts valid subagents and playbook", () => {
    const item = validateRegistryItem(structuredClone(base), { name: "ios-playbook", type: "pack" });
    if (item.type !== "pack") throw new Error("expected pack");
    expect(item.pack.subagents?.[0]?.name).toBe("ux_hig_reviewer");
    expect(item.pack.playbook?.orchestrator.name).toBe("ios-prd-playbook");
    expect(item.pack.playbook?.phases).toHaveLength(1);
  });

  test("rejects a non-snake-case subagent name and a traversal reference path", () => {
    const badName = structuredClone(base);
    (badName.pack.subagents[0] as { name: string }).name = "UX-Reviewer";
    expect(() => validateRegistryItem(badName, { name: "ios-playbook", type: "pack" })).toThrow("pack.subagents.0.name");

    const badRef = structuredClone(base);
    badRef.pack.playbook.orchestrator.references![0]!.name = "../escape.md";
    expect(() => validateRegistryItem(badRef, { name: "ios-playbook", type: "pack" })).toThrow("must be relative");
  });
});

describe("TOML multiline escaping", () => {
  test("escape then unescape is identity across backslashes and triple quotes", () => {
    const samples = [
      'Escape \\ and """ carefully.',
      "plain text with no specials",
      'a\\b"""c\\\\d',
      '"""',
      "\\",
      'trailing backslash \\',
      'nested """" quads and \\\\ pairs',
      "line one\nline two with \\ and \"\"\" markers"
    ];
    for (const sample of samples) {
      expect(unescapeTomlMultiline(escapeTomlMultiline(sample))).toBe(sample);
    }
  });

  test("the escaped form cannot prematurely close a multiline block", () => {
    expect(escapeTomlMultiline('x"""y')).not.toContain('"""');
  });
});
