#!/usr/bin/env python3
"""Deterministic playbook gate checker (engine-owned; regenerated by farrier).

Reads gates.json next to this script and verifies each gate's exit evidence
against the repository root (git toplevel, else the current directory). The
rules are declarative data (file-exists, glob-min, file-contains); this
script is the only executable, so an exported playbook never ships
model-authored code. A gate with no rules is reported as SKIP: its exit
evidence is review work (screenshot judgment, human approval), not files.

Usage: python3 check.py [gate-id ...]    # default: every gate in gates.json
Exit 0 when every requested rule passes; 1 otherwise.
"""
import json
import os
import re
import subprocess
import sys
from glob import glob


def repo_root():
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        # No git on PATH, or the call timed out: fall back to the cwd.
        return os.getcwd()
    if result.returncode == 0 and result.stdout.strip():
        return result.stdout.strip()
    return os.getcwd()


def check_rule(root, rule):
    kind = rule.get("kind")
    if kind == "file-exists":
        path = rule.get("path", "")
        return os.path.isfile(os.path.join(root, path)), f"file-exists {path}"
    if kind == "glob-min":
        pattern = rule.get("pattern", "")
        minimum = int(rule.get("min", 1))
        matches = [m for m in glob(os.path.join(root, pattern), recursive=True) if os.path.isfile(m)]
        return len(matches) >= minimum, f"glob-min {pattern} >= {minimum} (found {len(matches)})"
    if kind == "file-contains":
        path = rule.get("path", "")
        pattern = rule.get("pattern", "")
        label = f"file-contains {path} ~ /{pattern}/"
        try:
            with open(os.path.join(root, path), encoding="utf-8", errors="replace") as handle:
                text = handle.read()
        except OSError:
            return False, label + " (file missing)"
        return re.search(pattern, text) is not None, label
    return False, f"unknown rule kind {kind!r}"


def main(argv):
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, "gates.json"), encoding="utf-8") as handle:
        document = json.load(handle)
    gates = document.get("gates", [])
    requested = set(argv) if argv else None
    if requested:
        unknown = requested - {gate.get("gateId") for gate in gates}
        if unknown:
            print("UNKNOWN gate id(s): " + ", ".join(sorted(unknown)))
            return 1

    root = repo_root()
    failures = 0
    for gate in gates:
        gate_id = gate.get("gateId", "?")
        if requested and gate_id not in requested:
            continue
        rules = gate.get("rules", [])
        if not rules:
            print(f"SKIP {gate_id}: no deterministic rules; exit evidence is review work")
            continue
        for rule in rules:
            passed, label = check_rule(root, rule)
            print(f"{'PASS' if passed else 'FAIL'} {gate_id}: {label}")
            if not passed:
                failures += 1
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
